name=AirControl360
version=1.0.0
author=Herobrine Sah
maintainer=Herobrine Pixel <ashasah77@gmail.com>
sentence=Gesture control using MPU6050
paragraph=🚀 AirControl360 is a gesture and motion-based control library for Arduino/ESP32 using the MPU6050 sensor. It enables touchless control using hand movements like swipe, push, and pull.
category=Sensors
url=https://github.com/Herobrine-pixel/AirControl360
architectures=*
includes=AirControl360.cpp
