name=AirControl360
version=1.0.0
author=Herobrine Sah
maintainer=Herobrine Sah
sentence=Gesture control using MPU6050
paragraph=Detect swipe and push gestures using motion sensor.
category=Sensors
architectures=*
